---
server:
  host: localhost
  port: 11211

cluster:
  master:
    host: master
    port: 11249
  return:
    host: master
    port: 10036
  workers: 8

cache:
  redis:
    host: redis
    port: 6379
  io:
    bufferSize: 10240



