version: '2'

services:
  okserver:
    image: ok
    command: server
    environment:
      - "LOG_LEVEL:0"
      - "REDIS_HOST:redis"
      - "REDIS_PORT:6379"
    ports:
      - "11211:11211"

  okworker:
    image: ok
    command: worker
    environment:
      - "LOG_LEVEL:0"
      - "REDIS_HOST:redis"
      - "REDIS_PORT:6379"

  redis:
    image: redis:latest

