version: '2'

services:
  master:
    image: anthonyserious/okdataset:latest
    command: server
    environment:
      - "LOG_LEVEL=0"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    ports:
      - "11211:11211"

  worker:
    image: anthonyserious/okdataset:latest
    command: worker
    environment:
      - "LOG_LEVEL=0"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  redis:
    image: redis:latest

